name: Backend Lint & Format

on: workflow_call

jobs:
  lint_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run ES-Lint
        run: |
          echo "Linting code..."
          npm run lint

      - name: Check Code formatting
        run: |
          echo "Running code formatting using prettier..."
          npm run format:check
