name: Deploy to AWS with CDK

on:
  push:
    branches: [main, master]
  workflow_call: # allows ci.yml to trigger this as a reusable workflow

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy code aws cloud
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./aws/infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug OIDC Claims
        shell: bash
        run: |
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
          | jq -r '.value')

          echo "OIDC Token Claims"
          echo "$OIDC_TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::794314733919:role/GitHubActionsAWSAccess
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: aws/infrastructure/package-lock.json

      - name: Install CDK Deps
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Deploy CDK Stack
        run: npx cdk deploy --all --require-approval never
