name: Frontend Lint & Format

on: workflow_call

jobs:
  lint-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run ES-Lint
        run: npm run lint

      - name: Check prettier formatting
        run: npm run format:check
